Repository robot-lab/tinkoff-mlalgorithms, pull requests merged in 2018-08, with the labels that each got.

#24 Config ML
  logger.py
  ml_config.json
  models/k_nearest_neighbors.py
  models/linear_model.py
  models/random_forest.py
  parsers/config_parsers.py
  parsers/linear_model_parser.py
  parsers/parser.py
  requirements.txt
  shell.py
  tester.py
Labels: enhancement, technical debt, wontfix

#25 Removed duplicate config methods in tester;
  ml_config.json
  shell.py
  tester.py
Labels: enhancement, technical debt

#28 Add init file for working like module.
  __init__.py
  models/__init__.py
  parsers/__init__.py
Labels: technical debt, wontfix

#29 Bugfixes imports
  main.py
  mlalgorithms/__init__.py
  mlalgorithms/log_config.json
  mlalgorithms/logger.py
  mlalgorithms/ml_config.json
  mlalgorithms/models/__init__.py
  mlalgorithms/models/k_nearest_neighbors.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/models/model.py
  mlalgorithms/models/random_forest.py
  mlalgorithms/parsers/__init__.py
  mlalgorithms/parsers/config_parsers.py
  mlalgorithms/parsers/linear_model_parser.py
  mlalgorithms/parsers/parser.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
  setup.py
Labels: bug, enhancement

#32 Feature output format improvements
  main.py
  mlalgorithms/ml_config.json
  mlalgorithms/models/k_nearest_neighbors.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/models/model.py
  mlalgorithms/models/random_forest.py
  mlalgorithms/parsers/common_parser.py
  mlalgorithms/parsers/parser.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
Labels: enhancement

#37 Add function for reading and formatting train data.
  mlalgorithms/parsers/common_parser.py
Labels: enhancement, technical debt

#40 Expanded ML config
  mlalgorithms/logger.py
  mlalgorithms/ml_config.json
  mlalgorithms/models/catboost_model.py
  mlalgorithms/models/extra_trees.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/parsers/config_parsers.py
  mlalgorithms/shell.py
Labels: enhancement

#49 Added special methods for process and filter prediction
  mlalgorithms/ml_config.json
  mlalgorithms/parsers/common_parser.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
Labels: enhancement, invalid

#50 Frequency methods
  .gitignore
  README.md
  main.py
  mlalgorithms/logger.py
  mlalgorithms/ml_config.json
  mlalgorithms/models/catboost_model.py
  mlalgorithms/models/extra_trees.py
  mlalgorithms/models/frequency_analysis.py
  mlalgorithms/models/k_nearest_neighbors.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/parsers/common_parser.py
  mlalgorithms/parsers/config_parsers.py
  mlalgorithms/parsers/parser.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
  requirements.txt
Labels: enhancement

#52 Feature clustering model
  README.md
  mlalgorithms/ml_config.json
  mlalgorithms/models/clustering_model.py
Labels: enhancement

#54 Feature extend ml algorithms
  mlalgorithms/log_config.json
  mlalgorithms/logger.py
  mlalgorithms/ml_config.json
  mlalgorithms/parsers/common_parser.py
  mlalgorithms/parsers/config_parsers.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
Labels: enhancement

#56 Feature minor improvements
  mlalgorithms/checks.py
  mlalgorithms/logger.py
  mlalgorithms/ml_config.json
  mlalgorithms/models/catboost_model.py
  mlalgorithms/models/clustering_model.py
  mlalgorithms/models/ensemble_models.py
  mlalgorithms/models/frequency_analysis.py
  mlalgorithms/models/k_nearest_neighbors.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/models/model.py
  mlalgorithms/models/tree_models.py
  mlalgorithms/parsers/common_parser.py
  mlalgorithms/parsers/config_parsers.py
  mlalgorithms/parsers/parser.py
  mlalgorithms/shell.py
  mlalgorithms/tester.py
Labels: bug, technical debt

#58 Added simple implementations of IModel and IParser
  mlalgorithms/logger.py
  mlalgorithms/models/catboost_model.py
  mlalgorithms/models/clustering_model.py
  mlalgorithms/models/ensemble_models.py
  mlalgorithms/models/k_nearest_neighbors.py
  mlalgorithms/models/linear_model.py
  mlalgorithms/models/model.py
  mlalgorithms/models/tree_models.py
  mlalgorithms/parsers/parser.py
Labels: technical debt
